### ISSUE TITLE
Using <nuxt-link> with Stripe Menu

### ISSUE THREAD

**Issue by nevzatselcuk** [oleksiikhr/vue-stripe-menu#212]
Hi. I have a problem with stripe-menu when using link. If menu item is a link inside website, I must use link with nuxt-link as below.

**<nuxt-link tag=a :to="'/aboutpage'"></nuxt-link>**

Because if I use it with **<a href="/aboutpage"></a>**, NuxtJS render all page again. How to force stripe-menu link with nuxt-link

Is there a option for it? Thank you.

**Comment by Alexeykhr** [comment]
Hi.

```js
menu: [{ title: 'Nuxt link', element: 'nuxt-link', attributes: { to: '/page1' } }]
```

`element` property - Any global component or HTMLElement
