### ISSUE TITLE
Gap between menu and dropdown in safari

### ISSUE THREAD

**Issue by basbroens** [oleksiikhr/vue-stripe-menu#217]
when using vsm menu in safari there is a gap between the bar and the dropdown.

Probably due to the inline transform-translate css. 

Is there a workaround?

safari
![screen1](https://user-images.githubusercontent.com/24257007/117277920-954ee080-ae60-11eb-9822-ce2baae2a5cb.PNG)

all others
![screen2](https://user-images.githubusercontent.com/24257007/117277929-9849d100-ae60-11eb-80bf-caad29decf1b.PNG)

**Comment by Alexeykhr** [comment]
Sorry, I don't have Apple devices and Safari either. Having tried to check the component site through the online tool, it looks fine.

Is it in version 1.5 or 2.0? And the problem also exists on the [https://alexeykhr.github.io/vue-stripe-menu/](https://alexeykhr.github.io/vue-stripe-menu/) page?
